"""
HSK 5 hanzi → Vietnamese translations.
1,081 unique entries (filtered from 1,300 HSK 5 wordlist, removing overlaps
with HSK 1-4). Translations chosen for clarity in flashcard context.

Source list extracted from LiudmilaLV/json_hsk; Vietnamese translations
authored directly from hanzi using Claude's bilingual knowledge.
"""

HSK5_VI = {
    # ─── A ───
    '唉': 'tiếng thở dài', '爱护': 'yêu thương', '爱惜': 'nâng niu',
    '爱心': 'lòng nhân ái', '岸': 'bờ', '安慰': 'an ủi',
    '安装': 'lắp đặt', '把握': 'nắm bắt', '摆': 'bày',
    '班主任': 'giáo viên chủ nhiệm', '办理': 'xử lý', '棒': 'tuyệt',
    '傍晚': 'chập tối', '包裹': 'bưu kiện', '包含': 'bao gồm',
    '包括': 'bao gồm', '包子': 'bánh bao', '薄': 'mỏng',
    '宝贝': 'cục cưng', '宝贵': 'quý báu', '保持': 'duy trì',
    '保存': 'lưu giữ', '保留': 'giữ lại', '保险': 'bảo hiểm',
    '报道': 'đưa tin', '报告': 'báo cáo', '报社': 'tòa báo',
    '抱': 'ôm', '抱怨': 'phàn nàn', '背': 'lưng',
    '背景': 'bối cảnh', '被子': 'chăn', '悲观': 'bi quan',
    '本科': 'bậc cử nhân', '本领': 'bản lĩnh', '本质': 'bản chất',
    '比例': 'tỷ lệ', '彼此': 'lẫn nhau', '必然': 'tất nhiên',
    '必要': 'cần thiết', '毕竟': 'rốt cuộc', '避免': 'tránh',
    '编辑': 'biên tập', '鞭炮': 'pháo', '便': 'tiện',
    '辩论': 'tranh luận', '标点': 'dấu chấm câu', '标志': 'biểu tượng',
    '表达': 'biểu đạt', '表面': 'bề mặt', '表明': 'tỏ rõ',
    '表情': 'biểu cảm', '表现': 'biểu hiện', '冰激凌': 'kem',
    '病毒': 'vi rút', '玻璃': 'thủy tinh', '播放': 'phát',
    '脖子': 'cổ', '博物馆': 'bảo tàng', '补充': 'bổ sung',
    '不断': 'không ngừng', '不见得': 'chưa chắc', '不耐烦': 'mất kiên nhẫn',
    '不要紧': 'không sao', '部门': 'bộ phận', '不安': 'bất an',
    
    # ─── C ───
    '财产': 'tài sản', '采访': 'phỏng vấn', '采取': 'áp dụng',
    '彩虹': 'cầu vồng', '踩': 'giẫm', '参考': 'tham khảo',
    '参与': 'tham gia', '惭愧': 'xấu hổ', '操场': 'sân vận động',
    '操心': 'lo lắng', '册': 'tập', '测验': 'kiểm tra',
    '曾经': 'đã từng', '叉子': 'cái nĩa', '差距': 'khoảng cách',
    '插': 'cắm', '拆': 'tháo dỡ', '产品': 'sản phẩm',
    '产生': 'sinh ra', '常识': 'kiến thức cơ bản', '抄': 'chép',
    '超级': 'siêu cấp', '朝': 'hướng về', '潮湿': 'ẩm ướt',
    '吵': 'ồn ào', '吵架': 'cãi nhau', '炒': 'xào',
    '车库': 'nhà để xe', '车厢': 'toa tàu', '彻底': 'triệt để',
    '沉默': 'im lặng', '趁': 'nhân lúc', '称': 'gọi là',
    '称呼': 'cách xưng hô', '称赞': 'khen ngợi', '成分': 'thành phần',
    '成果': 'thành quả', '成就': 'thành tựu', '成立': 'thành lập',
    '成人': 'người trưởng thành', '成熟': 'trưởng thành', '成语': 'thành ngữ',
    '成长': 'trưởng thành', '诚恳': 'chân thành', '承担': 'gánh vác',
    '承认': 'thừa nhận', '承受': 'chịu đựng', '程度': 'mức độ',
    '程序': 'chương trình', '吃亏': 'thiệt thòi', '池塘': 'ao hồ',
    '迟早': 'sớm muộn', '持续': 'tiếp tục', '尺子': 'cây thước',
    '翅膀': 'cánh', '冲': 'xông', '充电器': 'bộ sạc',
    '充分': 'đầy đủ', '充满': 'tràn đầy', '重复': 'lặp lại',
    '宠物': 'thú cưng', '抽屉': 'ngăn kéo', '抽象': 'trừu tượng',
    '丑': 'xấu', '臭': 'thối', '出版': 'xuất bản',
    '出口': 'xuất khẩu', '出色': 'xuất sắc', '出席': 'có mặt',
    '初级': 'sơ cấp', '除非': 'trừ khi', '除夕': 'đêm giao thừa',
    '处理': 'xử lý', '传播': 'truyền bá', '传染': 'lây nhiễm',
    '传说': 'truyền thuyết', '传统': 'truyền thống', '窗帘': 'rèm cửa',
    '闯': 'xông vào', '创造': 'sáng tạo', '吹': 'thổi',
    '词汇': 'từ vựng', '辞职': 'từ chức', '此外': 'ngoài ra',
    '次要': 'thứ yếu', '刺激': 'kích thích', '匆忙': 'vội vàng',
    '从此': 'từ đó', '从而': 'do đó', '从前': 'ngày xưa',
    '从事': 'làm nghề', '粗糙': 'thô ráp', '促进': 'thúc đẩy',
    '促使': 'thúc giục', '醋': 'giấm', '催': 'giục',
    '存': 'lưu', '存在': 'tồn tại', '措施': 'biện pháp',
    '错误': 'sai lầm',
    
    # ─── D ───
    '答应': 'đồng ý', '达到': 'đạt được', '打工': 'làm thêm',
    '打交道': 'giao thiệp', '打喷嚏': 'hắt hơi', '打听': 'dò hỏi',
    '大方': 'hào phóng', '大厦': 'tòa nhà lớn', '大象': 'voi',
    '大型': 'cỡ lớn', '呆': 'ngẩn ngơ', '代表': 'đại diện',
    '代替': 'thay thế', '贷款': 'cho vay', '待遇': 'đãi ngộ',
    '担任': 'đảm nhiệm', '单纯': 'đơn thuần', '单调': 'đơn điệu',
    '单独': 'một mình', '单位': 'đơn vị', '单元': 'đơn nguyên',
    '耽误': 'làm lỡ', '胆小鬼': 'kẻ nhát gan', '淡': 'nhạt',
    '当地': 'địa phương', '当心': 'cẩn thận', '挡': 'chắn',
    '导演': 'đạo diễn', '导致': 'dẫn đến', '岛屿': 'hòn đảo',
    '到达': 'tới nơi', '倒霉': 'xui xẻo', '道德': 'đạo đức',
    '道理': 'đạo lý', '登记': 'đăng ký', '等待': 'chờ đợi',
    '等于': 'bằng', '滴': 'giọt', '的确': 'quả thực',
    '敌人': 'kẻ thù', '地道': 'đường hầm', '地理': 'địa lý',
    '地区': 'khu vực', '地毯': 'thảm', '地位': 'địa vị',
    '地震': 'động đất', '递': 'đưa', '点心': 'điểm tâm',
    '电池': 'pin', '电台': 'đài phát thanh', '钓': 'câu',
    '顶': 'đỉnh', '冻': 'đông cứng', '动画片': 'phim hoạt hình',
    '豆腐': 'đậu phụ', '逗': 'trêu', '独立': 'độc lập',
    '独特': 'độc đáo', '度过': 'trải qua', '断': 'gãy',
    '堆': 'đống', '对比': 'đối chiếu', '对待': 'đối xử',
    '对方': 'đối phương', '对手': 'đối thủ', '对象': 'đối tượng',
    '兑换': 'đổi tiền', '吨': 'tấn', '蹲': 'ngồi xổm',
    '顿': 'lần', '多亏': 'nhờ vào', '多余': 'dư thừa',
    '朵': 'đóa', '躲藏': 'ẩn nấp',
    
    # ─── E ───
    '恶劣': 'xấu xa', '耳环': 'bông tai',
    
    # ─── F ───
    '发表': 'đăng bài', '发愁': 'lo âu', '发达': 'phát đạt',
    '发抖': 'run rẩy', '发挥': 'phát huy', '发明': 'phát minh',
    '发票': 'hóa đơn', '发言': 'phát biểu', '罚款': 'phạt tiền',
    '法院': 'tòa án', '翻': 'lật', '繁荣': 'phồn vinh',
    '反而': 'ngược lại', '反复': 'lặp đi lặp lại', '反应': 'phản ứng',
    '反映': 'phản ánh', '反正': 'dù sao', '范围': 'phạm vi',
    '方': 'hình vuông', '方案': 'phương án', '妨碍': 'cản trở',
    '仿佛': 'tựa như', '非': 'không phải', '肥皂': 'xà phòng',
    '废话': 'lời thừa', '分别': 'chia tay', '分布': 'phân bố',
    '分配': 'phân phối', '分析': 'phân tích', '纷纷': 'tới tấp',
    '奋斗': 'phấn đấu', '风格': 'phong cách', '风俗': 'phong tục',
    '风险': 'rủi ro', '疯狂': 'điên cuồng', '讽刺': 'mỉa mai',
    '否定': 'phủ định', '否认': 'phủ nhận', '扶': 'đỡ',
    '服装': 'phục trang', '幅': 'bức', '辅导': 'hướng dẫn',
    '妇女': 'phụ nữ', '复制': 'sao chép',
    
    # ─── G ───
    '改革': 'cải cách', '改进': 'cải tiến', '改善': 'cải thiện',
    '改正': 'sửa chữa', '盖': 'đậy', '概括': 'khái quát',
    '概念': 'khái niệm', '干脆': 'dứt khoát', '干燥': 'khô',
    '赶紧': 'vội vàng', '赶快': 'mau lên', '感激': 'cảm kích',
    '感受': 'cảm nhận', '感想': 'cảm tưởng', '干活儿': 'làm việc',
    '钢铁': 'thép', '高档': 'cao cấp', '高级': 'cao cấp',
    '搞': 'làm', '告别': 'tạm biệt', '格外': 'đặc biệt',
    '隔壁': 'kế bên', '个别': 'cá biệt', '个人': 'cá nhân',
    '个性': 'cá tính', '各自': 'mỗi người', '根': 'gốc',
    '根本': 'căn bản', '工厂': 'nhà máy', '工程师': 'kỹ sư',
    '工具': 'công cụ', '工人': 'công nhân', '工业': 'công nghiệp',
    '公布': 'công bố', '公开': 'công khai', '公平': 'công bằng',
    '公寓': 'chung cư', '公元': 'Công nguyên', '公主': 'công chúa',
    '功能': 'chức năng', '恭喜': 'chúc mừng', '贡献': 'cống hiến',
    '沟通': 'giao tiếp', '构成': 'cấu thành', '姑姑': 'cô',
    '姑娘': 'cô gái', '古代': 'cổ đại', '古典': 'cổ điển',
    '股票': 'cổ phiếu', '骨头': 'xương', '鼓舞': 'khích lệ',
    '鼓掌': 'vỗ tay', '固定': 'cố định', '挂号': 'đăng ký khám',
    '观察': 'quan sát', '观点': 'quan điểm', '观念': 'quan niệm',
    '官': 'quan', '管子': 'ống', '冠军': 'quán quân',
    '光滑': 'trơn nhẵn', '光临': 'quang lâm', '光明': 'sáng lạn',
    '光盘': 'đĩa CD', '广场': 'quảng trường', '广大': 'rộng lớn',
    '广泛': 'rộng rãi', '归纳': 'quy nạp', '规矩': 'quy củ',
    '规律': 'quy luật', '规模': 'quy mô', '规则': 'quy tắc',
    '柜台': 'quầy', '滚': 'lăn', '锅': 'nồi',
    '国庆节': 'Quốc khánh', '国王': 'quốc vương', '果实': 'trái',
    '果然': 'quả nhiên', '过分': 'quá đáng', '过敏': 'dị ứng',
    '过期': 'quá hạn',
    
    # ─── H ───
    '哈': 'ha', '海关': 'hải quan', '海鲜': 'hải sản',
    '喊': 'hét', '行业': 'ngành nghề', '豪华': 'sang trọng',
    '好客': 'hiếu khách', '好奇': 'tò mò', '合法': 'hợp pháp',
    '合理': 'hợp lý', '合同': 'hợp đồng', '合影': 'chụp chung',
    '合作': 'hợp tác', '何必': 'cần gì', '何况': 'huống chi',
    '和平': 'hòa bình', '核心': 'cốt lõi', '恨': 'hận',
    '横': 'ngang', '哼': 'hừ', '后背': 'lưng',
    '后果': 'hậu quả', '呼吸': 'hít thở', '忽然': 'bỗng nhiên',
    '忽视': 'phớt lờ', '胡说': 'nói bậy', '胡同': 'ngõ hẻm',
    '壶': 'bình', '蝴蝶': 'bươm bướm', '糊涂': 'lú lẫn',
    '花生': 'lạc', '划': 'gạch', '华裔': 'người gốc Hoa',
    '滑': 'trơn', '化学': 'hóa học', '话题': 'chủ đề',
    '怀念': 'nhớ nhung', '怀孕': 'mang thai', '缓解': 'giảm bớt',
    '幻想': 'ảo tưởng', '慌张': 'hoảng hốt', '黄金': 'vàng',
    '灰': 'tro', '灰尘': 'bụi bặm', '灰心': 'nản lòng',
    '挥': 'vẫy', '恢复': 'hồi phục', '汇率': 'tỷ giá',
    '婚礼': 'lễ cưới', '婚姻': 'hôn nhân', '活跃': 'sôi nổi',
    '火柴': 'que diêm', '伙伴': 'bạn đồng hành', '或许': 'có lẽ',
    
    # ─── J ───
    '机器': 'máy móc', '肌肉': 'cơ bắp', '基本': 'cơ bản',
    '激烈': 'kịch liệt', '及格': 'đạt chuẩn', '急忙': 'vội vã',
    '急诊': 'cấp cứu', '集合': 'tập hợp', '集体': 'tập thể',
    '集中': 'tập trung', '计算': 'tính toán', '记录': 'ghi chép',
    '记忆': 'ký ức', '纪录': 'kỷ lục', '纪律': 'kỷ luật',
    '纪念': 'kỷ niệm', '系领带': 'thắt cà vạt', '寂寞': 'cô đơn',
    '夹子': 'cái kẹp', '家庭': 'gia đình', '家务': 'việc nhà',
    '家乡': 'quê hương', '嘉宾': 'khách mời', '甲': 'thứ nhất',
    '假设': 'giả thiết', '假装': 'giả vờ', '价值': 'giá trị',
    '驾驶': 'lái', '嫁': 'gả', '坚决': 'kiên quyết',
    '坚强': 'kiên cường', '肩膀': 'vai', '艰巨': 'gian khổ',
    '艰苦': 'gian nan', '兼职': 'kiêm nhiệm', '捡': 'nhặt',
    '剪刀': 'kéo cắt', '简历': 'sơ yếu lý lịch', '简直': 'thật là',
    '建立': 'xây dựng', '建设': 'xây dựng', '建议': 'đề xuất',
    '建筑': 'kiến trúc', '健身': 'rèn luyện', '键盘': 'bàn phím',
    '讲究': 'chú trọng', '讲座': 'bài giảng', '酱油': 'nước tương',
    '交换': 'trao đổi', '交际': 'giao tế', '交往': 'qua lại',
    '浇': 'tưới', '胶水': 'keo', '角度': 'góc độ',
    '狡猾': 'xảo quyệt', '教材': 'giáo trình', '教练': 'huấn luyện viên',
    '教训': 'bài học', '阶段': 'giai đoạn', '结实': 'chắc chắn',
    '接触': 'tiếp xúc', '接待': 'tiếp đãi', '接近': 'tiếp cận',
    '节省': 'tiết kiệm', '结构': 'cấu trúc', '结合': 'kết hợp',
    '结论': 'kết luận', '结账': 'tính tiền', '戒': 'cai',
    '戒指': 'nhẫn', '届': 'khóa', '借口': 'cái cớ',
    '金属': 'kim loại', '尽快': 'càng sớm càng tốt', '尽量': 'cố hết sức',
    '紧': 'chặt', '紧急': 'khẩn cấp', '谨慎': 'thận trọng',
    '尽': 'hết', '进步': 'tiến bộ', '进口': 'nhập khẩu',
    '近代': 'cận đại', '经典': 'kinh điển', '经商': 'kinh doanh',
    '经营': 'kinh doanh', '精力': 'tinh lực', '精神': 'tinh thần',
    '酒吧': 'quán bar', '救': 'cứu', '救护车': 'xe cứu thương',
    '舅舅': 'cậu', '居然': 'thậm chí', '桔子': 'quýt',
    '俱乐部': 'câu lạc bộ', '具备': 'sở hữu', '具体': 'cụ thể',
    '巨大': 'khổng lồ', '据说': 'nghe nói', '捐': 'quyên góp',
    '决赛': 'chung kết', '决心': 'quyết tâm', '角色': 'vai',
    '绝对': 'tuyệt đối', '军事': 'quân sự', '均匀': 'đồng đều',
    
    # ─── K ───
    '卡车': 'xe tải', '开发': 'khai thác', '开放': 'mở cửa',
    '开幕式': 'lễ khai mạc', '开水': 'nước sôi', '砍': 'chặt',
    '看不起': 'coi thường', '看望': 'thăm', '靠': 'dựa vào',
    '颗': 'hạt', '可见': 'có thể thấy', '可靠': 'đáng tin',
    '可怕': 'đáng sợ', '克': 'gam', '克服': 'khắc phục',
    '刻苦': 'chịu khó', '客观': 'khách quan', '课程': 'khóa học',
    '空间': 'không gian', '空闲': 'rảnh rỗi', '控制': 'kiểm soát',
    '口味': 'khẩu vị', '夸': 'khen', '夸张': 'phóng đại',
    '会计': 'kế toán', '宽': 'rộng', '昆虫': 'côn trùng',
    '扩大': 'mở rộng',
    
    # ─── L ───
    '辣椒': 'ớt', '拦': 'chặn lại', '烂': 'hư hỏng',
    '朗读': 'đọc to', '劳动': 'lao động', '劳驾': 'làm phiền',
    '老百姓': 'dân thường', '老板': 'ông chủ', '老婆': 'vợ',
    '老实': 'thật thà', '老鼠': 'chuột', '姥姥': 'bà ngoại',
    '乐观': 'lạc quan', '雷': 'sấm', '类型': 'loại hình',
    '冷淡': 'lạnh nhạt', '梨': 'lê', '厘米': 'cm',
    '离婚': 'ly hôn', '理论': 'lý thuyết', '理由': 'lý do',
    '力量': 'sức lực', '立方': 'lập phương', '立即': 'lập tức',
    '立刻': 'tức khắc', '利润': 'lợi nhuận', '利息': 'lãi suất',
    '利益': 'lợi ích', '利用': 'lợi dụng', '连忙': 'vội vã',
    '连续': 'liên tục', '联合': 'liên hợp', '恋爱': 'yêu đương',
    '良好': 'tốt đẹp', '粮食': 'lương thực', '亮': 'sáng',
    '了不起': 'phi thường', '列车': 'tàu hỏa', '临时': 'tạm thời',
    '灵活': 'linh hoạt', '铃': 'chuông', '零件': 'linh kiện',
    '零食': 'đồ ăn vặt', '领导': 'lãnh đạo', '领域': 'lĩnh vực',
    '浏览': 'lướt qua', '流传': 'lưu truyền', '流泪': 'rơi lệ',
    '龙': 'rồng', '漏': 'rò rỉ', '陆地': 'đất liền',
    '陆续': 'lần lượt', '录取': 'tuyển sinh', '录音': 'ghi âm',
    '轮流': 'luân phiên', '论文': 'luận văn', '逻辑': 'logic',
    '落后': 'lạc hậu',
    
    # ─── M ───
    '骂': 'mắng', '麦克风': 'micro', '馒头': 'màn thầu',
    '满足': 'thỏa mãn', '毛': 'lông', '毛病': 'tật xấu',
    '矛盾': 'mâu thuẫn', '冒险': 'mạo hiểm', '贸易': 'mậu dịch',
    '眉毛': 'lông mày', '煤炭': 'than đá', '美术': 'mỹ thuật',
    '魅力': 'sức hấp dẫn', '梦想': 'giấc mơ', '迷路': 'lạc đường',
    '谜语': 'câu đố', '蜜蜂': 'ong mật', '密切': 'mật thiết',
    '秘密': 'bí mật', '秘书': 'thư ký', '面对': 'đối mặt',
    '面积': 'diện tích', '面临': 'đối diện', '苗条': 'mảnh mai',
    '描写': 'miêu tả', '敏感': 'nhạy cảm', '名牌': 'thương hiệu nổi tiếng',
    '名片': 'danh thiếp', '名胜古迹': 'danh lam thắng cảnh', '明确': 'rõ ràng',
    '明显': 'rõ rệt', '明信片': 'bưu thiếp', '明星': 'ngôi sao',
    '命令': 'mệnh lệnh', '命运': 'số phận', '摸': 'sờ',
    '模仿': 'bắt chước', '模糊': 'mơ hồ', '模特': 'người mẫu',
    '摩托车': 'xe máy', '陌生': 'xa lạ', '某': 'một nào đó',
    '木头': 'gỗ', '目标': 'mục tiêu', '目录': 'mục lục',
    '目前': 'hiện nay',
    
    # ─── N ───
    '哪怕': 'cho dù', '难怪': 'thảo nào', '难免': 'khó tránh khỏi',
    '脑袋': 'đầu', '内部': 'nội bộ', '内科': 'nội khoa',
    '嫩': 'mềm non', '能干': 'năng lực', '能源': 'năng lượng',
    '嗯': 'ừ', '年代': 'thập niên', '年纪': 'tuổi tác',
    '念': 'đọc', '宁可': 'thà rằng', '牛仔裤': 'quần bò',
    '农民': 'nông dân', '农业': 'nông nghiệp', '浓': 'đậm đặc',
    '女士': 'quý bà',
    
    # ─── O P ───
    '欧洲': 'châu Âu', '偶然': 'tình cờ', '拍': 'vỗ',
    '派': 'phái', '盼望': 'mong đợi', '培养': 'bồi dưỡng',
    '赔偿': 'bồi thường', '佩服': 'khâm phục', '配合': 'phối hợp',
    '盆': 'chậu', '碰见': 'gặp gỡ', '披': 'khoác',
    '批': 'phê', '批准': 'phê duyệt', '披风': 'áo choàng',
    '疲劳': 'mệt mỏi', '匹': 'con (ngựa)', '片': 'mảnh',
    '片面': 'phiến diện', '飘': 'bay phấp phới', '拼音': 'phiên âm',
    '频道': 'kênh', '平': 'bằng phẳng', '平安': 'bình an',
    '平常': 'bình thường', '平等': 'bình đẳng', '平方': 'bình phương',
    '平衡': 'cân bằng', '平静': 'yên tĩnh', '平均': 'trung bình',
    '评价': 'đánh giá', '凭': 'dựa vào', '迫切': 'cấp thiết',
    '破产': 'phá sản', '破坏': 'phá hoại', '朴素': 'mộc mạc',
    '期待': 'mong đợi', '期间': 'thời gian',
    
    # ─── Q ───
    '其余': 'còn lại', '奇迹': 'kỳ tích', '企图': 'mưu đồ',
    '企业': 'doanh nghiệp', '启发': 'khai sáng', '气氛': 'bầu không khí',
    '汽油': 'xăng', '谦虚': 'khiêm tốn', '签': 'ký',
    '前途': 'tương lai', '浅': 'cạn', '欠': 'nợ',
    '枪': 'súng', '强调': 'nhấn mạnh', '强烈': 'mãnh liệt',
    '墙': 'tường', '抢': 'cướp', '悄悄': 'lặng lẽ',
    '瞧': 'nhìn', '巧妙': 'khéo léo', '切': 'cắt',
    '亲爱': 'thân yêu', '亲切': 'thân thiết', '亲自': 'đích thân',
    '勤奋': 'siêng năng', '青': 'xanh lam', '青春': 'tuổi xuân',
    '青少年': 'thanh thiếu niên', '轻视': 'xem nhẹ', '轻易': 'dễ dàng',
    '清淡': 'thanh đạm', '情景': 'tình cảnh', '情绪': 'cảm xúc',
    '请求': 'yêu cầu', '庆祝': 'chúc mừng', '球迷': 'fan bóng',
    '区别': 'phân biệt', '取消': 'hủy bỏ', '娶': 'cưới (vợ)',
    '去世': 'qua đời', '圈': 'vòng', '权力': 'quyền lực',
    '权利': 'quyền lợi', '全面': 'toàn diện', '劝': 'khuyên',
    '缺乏': 'thiếu', '确定': 'xác định', '确认': 'xác nhận',
    '群': 'đàn',
    
    # ─── R ───
    '燃烧': 'cháy', '绕': 'vòng quanh', '惹': 'chọc',
    '热爱': 'yêu thích', '热烈': 'nhiệt liệt', '热心': 'nhiệt tình',
    '人才': 'nhân tài', '人口': 'dân số', '人类': 'loài người',
    '人民币': 'nhân dân tệ', '人生': 'cuộc đời', '人事': 'nhân sự',
    '人物': 'nhân vật', '人员': 'nhân viên', '忍不住': 'không nhịn được',
    '日常': 'hàng ngày', '日历': 'lịch', '日期': 'ngày tháng',
    '日用品': 'đồ dùng hàng ngày', '融化': 'tan chảy', '荣幸': 'vinh hạnh',
    '荣誉': 'danh dự', '如何': 'như thế nào', '如今': 'ngày nay',
    '软': 'mềm', '软件': 'phần mềm', '弱': 'yếu',
    
    # ─── S ───
    '洒': 'rải', '嗓子': 'cổ họng', '色彩': 'màu sắc',
    '杀': 'giết', '沙漠': 'sa mạc', '沙滩': 'bãi cát',
    '傻': 'ngốc', '晒': 'phơi', '删除': 'xóa',
    '闪电': 'tia chớp', '善良': 'lương thiện', '善于': 'giỏi về',
    '扇子': 'cái quạt', '伤害': 'tổn hại', '商品': 'hàng hóa',
    '商务': 'thương mại', '商业': 'thương mại', '上当': 'mắc lừa',
    '蛇': 'rắn', '舍不得': 'tiếc rẻ', '设备': 'thiết bị',
    '设计': 'thiết kế', '设施': 'cơ sở vật chất', '射击': 'bắn',
    '摄影': 'nhiếp ảnh', '伸': 'duỗi', '深刻': 'sâu sắc',
    '神话': 'thần thoại', '神秘': 'thần bí', '升': 'lên',
    '生产': 'sản xuất', '生动': 'sinh động', '生长': 'sinh trưởng',
    '声调': 'thanh điệu', '绳子': 'sợi dây', '省略': 'lược bỏ',
    '胜利': 'thắng lợi', '失眠': 'mất ngủ', '失去': 'đánh mất',
    '失业': 'thất nghiệp', '诗': 'thơ', '狮子': 'sư tử',
    '湿润': 'ẩm ướt', '石头': 'đá', '时差': 'chênh lệch giờ',
    '时代': 'thời đại', '时刻': 'thời khắc', '时髦': 'thời thượng',
    '时期': 'thời kỳ', '实话': 'lời thật', '实践': 'thực hành',
    '实习': 'thực tập', '实现': 'thực hiện', '实验': 'thí nghiệm',
    '实用': 'thực dụng', '食物': 'thức ăn', '使劲儿': 'gắng sức',
    '始终': 'từ đầu đến cuối', '士兵': 'binh sĩ', '事实': 'sự thật',
    '事物': 'sự vật', '事先': 'trước đó', '试卷': 'đề thi',
    '收获': 'thu hoạch', '收据': 'biên lai', '手工': 'thủ công',
    '手术': 'phẫu thuật', '手套': 'găng tay', '手续': 'thủ tục',
    '手指': 'ngón tay', '寿命': 'tuổi thọ', '受伤': 'bị thương',
    '书架': 'kệ sách', '梳子': 'lược', '舒适': 'thoải mái',
    '蔬菜': 'rau', '熟练': 'thành thạo', '属于': 'thuộc về',
    '鼠标': 'chuột máy tính', '数': 'đếm', '数据': 'dữ liệu',
    '数码': 'kỹ thuật số', '摔倒': 'vấp ngã', '甩': 'vung',
    '双方': 'hai bên', '税': 'thuế', '说不定': 'không chừng',
    '说服': 'thuyết phục', '丝绸': 'tơ lụa', '丝毫': 'mảy may',
    '私人': 'riêng tư', '思考': 'tư duy', '思想': 'tư tưởng',
    '撕': 'xé', '寺庙': 'chùa', '似乎': 'dường như',
    '似的': 'giống như', '搜索': 'tìm kiếm', '宿舍': 'ký túc xá',
    '随身': 'mang theo', '随时': 'bất cứ lúc nào', '随手': 'tiện tay',
    '碎': 'vỡ', '损失': 'tổn thất', '缩短': 'rút ngắn',
    '所': 'nơi', '所谓': 'cái gọi là', '锁': 'khóa',
    
    # ─── T ───
    '塔': 'tháp', '台阶': 'bậc thang', '太极拳': 'thái cực quyền',
    '太太': 'bà', '谈判': 'đàm phán', '坦率': 'thẳng thắn',
    '烫': 'bỏng', '桃': 'đào', '逃': 'trốn',
    '逃避': 'trốn tránh', '套': 'bộ', '特色': 'đặc sắc',
    '特殊': 'đặc thù', '特征': 'đặc trưng', '疼爱': 'thương yêu',
    '提': 'xách', '提倡': 'đề xướng', '提纲': 'đề cương',
    '提问': 'đặt câu hỏi', '题目': 'đề mục', '体会': 'cảm nhận',
    '体贴': 'chu đáo', '体现': 'thể hiện', '体验': 'trải nghiệm',
    '天空': 'bầu trời', '天真': 'ngây thơ', '田野': 'đồng ruộng',
    '调皮': 'tinh nghịch', '调整': 'điều chỉnh', '挑战': 'thách thức',
    '挑': 'gánh', '通常': 'thông thường', '统一': 'thống nhất',
    '痛苦': 'đau khổ', '痛快': 'thỏa thích', '投入': 'đầu tư',
    '投资': 'đầu tư', '透明': 'trong suốt', '突出': 'nổi bật',
    '土地': 'đất đai', '土豆': 'khoai tây', '吐': 'nôn',
    '兔子': 'thỏ', '团': 'đoàn', '推': 'đẩy',
    '推辞': 'từ chối', '推广': 'phổ biến', '推荐': 'giới thiệu',
    '退': 'lùi', '退步': 'thụt lùi', '退休': 'nghỉ hưu',
    
    # ─── W ───
    '歪': 'lệch', '外公': 'ông ngoại', '外交': 'ngoại giao',
    '完美': 'hoàn hảo', '完善': 'hoàn thiện', '完整': 'hoàn chỉnh',
    '玩具': 'đồ chơi', '万一': 'phòng khi', '王子': 'hoàng tử',
    '往返': 'đi về', '危害': 'nguy hại', '威胁': 'đe dọa',
    '微笑': 'mỉm cười', '违反': 'vi phạm', '围巾': 'khăn quàng',
    '围绕': 'xoay quanh', '唯一': 'duy nhất', '维护': 'bảo vệ',
    '维修': 'sửa chữa', '伟大': 'vĩ đại', '尾巴': 'đuôi',
    '委屈': 'oan ức', '委托': 'ủy thác', '未必': 'chưa chắc',
    '未来': 'tương lai', '位于': 'tọa lạc', '位置': 'vị trí',
    '胃': 'dạ dày', '胃口': 'cảm giác thèm ăn', '温暖': 'ấm áp',
    '温柔': 'dịu dàng', '文件': 'tài liệu', '文具': 'văn phòng phẩm',
    '文明': 'văn minh', '文学': 'văn học', '文字': 'văn tự',
    '闻': 'ngửi', '吻': 'hôn', '稳定': 'ổn định',
    '问候': 'thăm hỏi', '卧室': 'phòng ngủ', '握手': 'bắt tay',
    '屋子': 'căn phòng', '无奈': 'bất lực', '无数': 'vô số',
    '无所谓': 'không sao', '武器': 'vũ khí', '武术': 'võ thuật',
    '勿': 'chớ', '物理': 'vật lý', '物质': 'vật chất',
    '雾': 'sương mù',
    
    # ─── X ───
    '吸取': 'tiếp thu', '吸收': 'hấp thụ', '系统': 'hệ thống',
    '戏剧': 'kịch', '细节': 'chi tiết', '瞎': 'mù',
    '下载': 'tải xuống', '吓': 'dọa', '夏令营': 'trại hè',
    '鲜艳': 'rực rỡ', '显得': 'có vẻ', '显然': 'rõ ràng',
    '显示': 'hiển thị', '县': 'huyện', '现代': 'hiện đại',
    '现实': 'hiện thực', '现象': 'hiện tượng', '限制': 'giới hạn',
    '相处': 'sống chung', '相当': 'tương đối', '相对': 'tương đối',
    '相关': 'liên quan', '相似': 'tương tự', '香肠': 'xúc xích',
    '享受': 'hưởng thụ', '想念': 'nhớ nhung', '想象': 'tưởng tượng',
    '项': 'hạng mục', '项链': 'dây chuyền', '项目': 'dự án',
    '象棋': 'cờ tướng', '象征': 'tượng trưng', '消费': 'tiêu dùng',
    '消化': 'tiêu hóa', '消极': 'tiêu cực', '消失': 'biến mất',
    '销售': 'bán hàng', '小麦': 'lúa mì', '小气': 'keo kiệt',
    '小说': 'tiểu thuyết', '小偷': 'kẻ trộm', '孝顺': 'hiếu thảo',
    '效率': 'hiệu suất', '歇': 'nghỉ', '斜': 'nghiêng',
    '协调': 'hài hòa', '协商': 'thương lượng', '心理': 'tâm lý',
    '心脏': 'tim', '欣赏': 'thưởng thức', '辛苦': 'vất vả',
    '信号': 'tín hiệu', '信任': 'tin tưởng', '形成': 'hình thành',
    '形容': 'mô tả', '形式': 'hình thức', '形势': 'tình hình',
    '形象': 'hình tượng', '形状': 'hình dạng', '行动': 'hành động',
    '行人': 'người đi đường', '行为': 'hành vi', '幸亏': 'may mà',
    '幸运': 'may mắn', '性别': 'giới tính', '性质': 'tính chất',
    '兄弟': 'anh em', '胸': 'ngực', '雄伟': 'hùng vĩ',
    '休闲': 'thư giãn', '修改': 'sửa đổi', '虚心': 'khiêm tốn',
    '叙述': 'tường thuật', '宣布': 'tuyên bố', '宣传': 'tuyên truyền',
    '学历': 'học lực', '学术': 'học thuật', '学问': 'học vấn',
    '寻找': 'tìm kiếm', '询问': 'hỏi thăm', '迅速': 'nhanh chóng',
    
    # ─── Y ───
    '押金': 'tiền đặt cọc', '牙齿': 'răng', '延长': 'kéo dài',
    '严肃': 'nghiêm túc', '宴会': 'tiệc', '阳台': 'ban công',
    '痒': 'ngứa', '样式': 'kiểu dáng', '腰': 'eo',
    '摇': 'lắc', '咬': 'cắn', '要不': 'hay là',
    '夜': 'đêm', '业务': 'nghiệp vụ', '业余': 'nghiệp dư',
    '一辈子': 'cả đời', '一旦': 'một khi', '一律': 'thống nhất',
    '一再': 'hết lần này đến lần khác', '一致': 'nhất trí', '依然': 'vẫn',
    '移动': 'di động', '移民': 'di dân', '遗憾': 'tiếc nuối',
    '疑问': 'nghi vấn', '乙': 'thứ hai', '以及': 'cũng như',
    '以来': 'kể từ', '亿': 'tỷ', '义务': 'nghĩa vụ',
    '议论': 'bàn luận', '意外': 'bất ngờ', '意义': 'ý nghĩa',
    '因而': 'do đó', '因素': 'nhân tố', '银': 'bạc',
    '英俊': 'tuấn tú', '英雄': 'anh hùng', '迎接': 'đón tiếp',
    '营养': 'dinh dưỡng', '营业': 'kinh doanh', '影子': 'cái bóng',
    '应付': 'đối phó', '应聘': 'ứng tuyển', '应用': 'ứng dụng',
    '硬': 'cứng', '硬件': 'phần cứng', '拥抱': 'ôm',
    '拥挤': 'chen chúc', '勇气': 'dũng khí', '用功': 'chăm chỉ',
    '用途': 'công dụng', '优点': 'ưu điểm', '优势': 'ưu thế',
    '悠久': 'lâu dài', '犹豫': 'do dự', '油炸': 'chiên',
    '游览': 'tham quan', '有利': 'có lợi', '幼儿园': 'trường mẫu giáo',
    '娱乐': 'giải trí', '与其': 'thay vì', '语气': 'ngữ điệu',
    '玉米': 'ngô', '预报': 'dự báo', '预订': 'đặt trước',
    '预防': 'phòng ngừa', '元旦': 'Tết Dương lịch', '员工': 'nhân viên',
    '原料': 'nguyên liệu', '原则': 'nguyên tắc', '圆': 'tròn',
    '愿望': 'nguyện vọng', '乐器': 'nhạc cụ', '晕': 'chóng mặt',
    '运气': 'vận may', '运输': 'vận chuyển', '运用': 'vận dụng',
    
    # ─── Z ───
    '灾害': 'thiên tai', '再三': 'nhiều lần', '赞成': 'tán thành',
    '赞美': 'ca ngợi', '糟糕': 'tồi tệ', '造成': 'gây ra',
    '则': 'thì', '责备': 'trách móc', '摘': 'hái',
    '窄': 'hẹp', '粘贴': 'dán', '展开': 'mở ra',
    '展览': 'triển lãm', '占': 'chiếm', '战争': 'chiến tranh',
    '长辈': 'bậc trưởng thượng', '涨': 'dâng lên', '掌握': 'nắm vững',
    '账户': 'tài khoản', '招待': 'tiếp đãi', '着火': 'bốc cháy',
    '着凉': 'cảm lạnh', '召开': 'triệu tập', '照常': 'như thường',
    '哲学': 'triết học', '真实': 'chân thực', '针对': 'nhắm vào',
    '诊断': 'chẩn đoán', '阵': 'trận', '振动': 'rung',
    '争论': 'tranh luận', '争取': 'giành lấy', '征求': 'xin ý kiến',
    '睁': 'mở mắt', '整个': 'toàn bộ', '整齐': 'gọn gàng',
    '整体': 'tổng thể', '正': 'đúng', '正常': 'bình thường',
    '正方形': 'hình vuông', '正好': 'vừa đúng', '正经': 'đứng đắn',
    '正义': 'chính nghĩa', '证件': 'giấy tờ', '证据': 'chứng cứ',
    '政府': 'chính phủ', '政治': 'chính trị', '挣': 'kiếm tiền',
    '支': 'cây (bút)', '支票': 'séc', '执照': 'giấy phép',
    '直': 'thẳng', '指导': 'chỉ đạo', '指挥': 'chỉ huy',
    '至今': 'cho đến nay', '至于': 'còn về', '志愿者': 'tình nguyện viên',
    '制定': 'đặt ra', '制度': 'chế độ', '制造': 'chế tạo',
    '制作': 'làm ra', '治疗': 'điều trị', '秩序': 'trật tự',
    '智慧': 'trí tuệ', '中介': 'trung gian', '中心': 'trung tâm',
    '中旬': 'trung tuần', '种类': 'chủng loại', '重大': 'trọng đại',
    '重量': 'trọng lượng', '猪': 'lợn', '逐步': 'từng bước',
    '逐渐': 'dần dần', '主持': 'chủ trì', '主动': 'chủ động',
    '主观': 'chủ quan', '主人': 'chủ nhân', '主任': 'chủ nhiệm',
    '主题': 'chủ đề', '主席': 'chủ tịch', '主张': 'chủ trương',
    '煮': 'luộc', '注册': 'đăng ký', '祝福': 'chúc phúc',
    '抓': 'bắt', '抓紧': 'nắm chặt', '专家': 'chuyên gia',
    '专心': 'chuyên tâm', '转变': 'chuyển biến', '转告': 'chuyển lời',
    '装': 'giả vờ', '装饰': 'trang trí', '装修': 'sửa nhà',
    '状况': 'tình trạng', '状态': 'trạng thái', '撞': 'đâm',
    '追': 'đuổi', '追求': 'theo đuổi', '资格': 'tư cách',
    '资金': 'tiền vốn', '资料': 'tư liệu', '资源': 'tài nguyên',
    '紫': 'tím', '自从': 'từ khi', '自动': 'tự động',
    '自豪': 'tự hào', '自觉': 'tự giác', '自私': 'ích kỷ',
    '自由': 'tự do', '自愿': 'tự nguyện', '字母': 'chữ cái',
    '字幕': 'phụ đề', '综合': 'tổng hợp', '总裁': 'tổng giám đốc',
    '总共': 'tổng cộng', '总理': 'thủ tướng', '总算': 'cuối cùng',
    '总统': 'tổng thống', '总之': 'tóm lại', '阻止': 'ngăn cản',
    '组': 'nhóm', '组成': 'cấu thành', '组合': 'tổ hợp',
    '组织': 'tổ chức', '最初': 'ban đầu', '罪犯': 'tội phạm',
    '尊敬': 'tôn kính', '遵守': 'tuân thủ', '作品': 'tác phẩm',
    '作为': 'với tư cách', '作文': 'bài văn',
    
    # ─── Missing entries (146 added for full coverage) ───
    '比如': 'ví dụ', '必需': 'cần thiết', '丙': 'thứ ba',
    '不必': 'không cần', '不得了': 'rất nghiêm trọng', '不好意思': 'ngại quá',
    '不免': 'không tránh khỏi', '不然': 'nếu không', '不如': 'không bằng',
    '不足': 'không đủ', '布': 'vải', '步骤': 'bước',
    '残疾': 'tàn tật', '厕所': 'nhà vệ sinh', '差别': 'khác biệt',
    '长途': 'đường dài', '朝代': 'triều đại', '乘': 'cưỡi',
    '池子': 'ao', '除': 'loại bỏ', '传递': 'truyền đạt',
    '磁带': 'băng từ', '当代': 'đương đại', '岛': 'đảo',
    '倒': 'đổ ngược', '登机牌': 'thẻ lên máy bay', '等候': 'chờ đợi',
    '点头': 'gật đầu', '丁': 'thứ tư', '洞': 'hang',
    '对于': 'đối với', '凡是': 'phàm là', '方式': 'phương thức',
    '房东': 'chủ nhà', '肺': 'phổi', '费用': 'chi phí',
    '服从': 'phục tùng', '付款': 'thanh toán', '高速': 'tốc độ cao',
    '鸽子': 'chim bồ câu', '革命': 'cách mạng', '更加': 'càng thêm',
    '功夫': 'công phu', '古老': 'cổ xưa', '固体': 'thể rắn',
    '雇佣': 'thuê', '乖': 'ngoan', '拐弯': 'rẽ',
    '怪不得': 'thảo nào', '关闭': 'đóng', '关怀': 'quan tâm',
    '罐头': 'đồ hộp', '光荣': 'vinh quang', '国籍': 'quốc tịch',
    '胡须': 'râu', '滑冰': 'trượt băng', '划船': 'chèo thuyền',
    '黄瓜': 'dưa chuột', '皇帝': 'hoàng đế', '皇后': 'hoàng hậu',
    '假如': 'giả sử', '煎': 'rán', '健身房': 'phòng gym',
    '降落': 'hạ cánh', '郊区': 'ngoại ô', '接着': 'tiếp theo',
    '节': 'tiết', '解放': 'giải phóng', '解说员': 'người bình luận',
    '戒烟': 'cai thuốc', '尽力': 'cố hết sức', '景色': 'cảnh sắc',
    '敬爱': 'kính yêu', '卷': 'cuộn', '看来': 'xem ra',
    '抗议': 'phản đối', '烤鸭': 'vịt quay', '恐怖': 'kinh khủng',
    '矿泉水': 'nước khoáng', '蜡烛': 'nến', '来自': 'đến từ',
    '狼': 'sói', '类': 'loại', '礼拜天': 'Chủ nhật',
    '粒': 'hạt', '连续剧': 'phim dài tập', '零钱': 'tiền lẻ',
    '露': 'sương', '棉花': 'bông', '民主': 'dân chủ',
    '难看': 'khó coi', '排队': 'xếp hàng', '排球': 'bóng chuyền',
    '皮鞋': 'giày da', '品种': 'chủng loại', '牵': 'dắt',
    '侵略': 'xâm lược', '勤劳': 'siêng năng', '趋势': 'xu hướng',
    '嚷': 'la hét', '舌头': 'lưỡi', '身材': 'vóc dáng',
    '身份': 'thân phận', '神经': 'thần kinh', '时尚': 'thời thượng',
    '实行': 'thực hiện', '是否': 'có hay không', '输入': 'nhập vào',
    '摔': 'ngã', '缩小': 'thu nhỏ', '特意': 'cố ý',
    '体积': 'thể tích', '通讯': 'thông tin liên lạc', '铜': 'đồng',
    '统治': 'thống trị', '弯': 'cong', '系': 'buộc',
    '现金': 'tiền mặt', '橡皮': 'cục tẩy', '消灭': 'tiêu diệt',
    '小吃': 'món ăn vặt', '小伙子': 'chàng trai', '信封': 'phong bì',
    '信息': 'thông tin', '训练': 'huấn luyện', '要是': 'nếu',
    '液体': 'thể lỏng', '一路': 'suốt đường', '硬币': 'đồng xu',
    '优惠': 'ưu đãi', '优美': 'tao nhã', '缘故': 'lý do',
    '占线': 'máy bận', '珍惜': 'trân trọng', '挣钱': 'kiếm tiền',
    '执行': 'thi hành', '钟': 'đồng hồ', '周到': 'chu đáo',
    '竹子': 'tre', '嘱咐': 'dặn dò', '姿势': 'tư thế',
    '咨询': 'tư vấn', '宗教': 'tôn giáo', '祖国': 'tổ quốc',
    '祖先': 'tổ tiên', '醉': 'say',
}
